RNN_STATE_DIM: 512  # the feature dimension for RNNs
RNN_CELL_DEPTH: 2  # the depth for RNNs

EMBEDDING_VECOTR_SIZE: 320  # the size of embedding vector in the network

LEAK_VALUE: 0.05  # the value of leak relu

CUBE_LEN: 32  # used to describe the resolution of the voxelization map
BOUNDING_BOX_SIZE: 6 # the size of feature vector of bounding box

TRAIN:
  BATCH_SIZE: 10  # mini batch size
  GPU_ID: [0, 1, 2, 3] # the gpus for training

  # Loss hyperparameters
  VOXEL_BBOX_LOSS_RATIO: 0.4  # The training loss weight
  GRAPH_REC_KL_LOSS_RATIO: 0.995

  RECON_GEN_INITIAL_LOSS_RATIO: 1.0   # control the influence between reconstruction and generation loss
  RECON_GEN_RATIO_GAMMA: 0.9
  RECON_GEN_DECAY_STEP: 1500
  KL_ANNEAL_ITER: 72000
  FINAL_KL_RATIO: 0.8

  # Learning rate
  VERT_LEARNING_RATE: 0.6   # Decay the learning rate
  VERT_GAMMA: 0.9
  VERT_LR_DECAY_STEP: 2300 

  EDGE_LEARNING_RATE: 0.1
  EDGE_GAMMA: 0.9
  EDGE_LR_DECAY_STEP: 1850

  GRAPH_GEN_LEARNING_RATE: 0.1
  GRAPH_GEN_GAMMA: 0.9
  GRAPH_GEN_LR_DECAY_STEP: 1600

  ITER_NUM: 80000   # Total training iteration number

  SNAPSHOT_FREQ: 2000  # The frequency to save model snapshot and summary
  SUMMARY_FREQ: 20

  ITERATION_NUM: 3  # the iteration number when exchange geometry and structure information
  DROPOUT_KEEP_PROB: 0.5

  MAX_GRADIENT_NORM: 0.5
  MOMENTUM_VALUE: 0.9
  RANDOM_SEED: 20

  OPTIMIZER_TYPE: "momentum"

  VOXEL_DEFAULT_VALUE: 0.1

  DIR_PATH: "training_data/"
  RESULTS_DIRECTORY: 'nn_exp_results/reconstruction_results/'
  LOG_DIRECTORY: 'nn_exp_results/logs/'
  MODEL_DIRECTORY: 'nn_exp_results/models/'

  PRETRAINED_MODEL_PATH: ""

  SHAPE_NAME: "motorbike" # "motorbike"/"chair"/"airplane"/"guitar"/"lamp"/"toy_examples"

TEST:
  GPU_ID: [7] # the gpus for testing

  SAMPLE_SIZE: 10
  SHAPE_NAME: "motorbike" # "motorbike"/"chair"/"airplane"/"guitar"/"lamp"/"toy_examples"

  RESULTS_DIRECTORY: 'nn_exp_results/testing_results/'
  PRETRAINED_MODEL_PATH: ''
